import { cookies } from "next/headers";

import { ThemeProvider } from "@/components/provider/theme-provider";
import { CustomProvider } from "@/state/store";

import "@/app/globals.css";

import { Montserrat } from "next/font/google";

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const getTheme = () => {
  const cookieStore = cookies();
  const themeCookie = cookieStore.get("theme");
  const theme = themeCookie ? themeCookie.value : "dark";

  return theme;
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const theme = getTheme();

  return (
    <html lang="en" className={theme} style={{ colorScheme: theme }}>
      <body className={montserrat.variable} id="body">
        <ThemeProvider attribute="class" defaultTheme="dark" enableSystem disableTransitionOnChange>
          <CustomProvider>{children}</CustomProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
